language: python
python:
  - 2.7

install: pip install -r requirements.txt

before_script: rm --recursive --force --verbose *.pyc

script:
  - python manage.py test --exe

notifications:
  email: false
